source 'https://rubygems.org'


gem 'rails', '4.1.8'
group :production do
	gem 'pg'
	gem 'rails_log_stdout',				github: 'heroku/rails_log_stdout'
	gem 'rails3_serve_static_assets',	github: 'heroku/rails3_serve_static_assets'
end
group :development do
	gem 'sqlite3'
end
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise', '~> 3.4.1'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'acts_as_votable', '~> 0.10.0'
gem 'simple_form', '~> 3.1.0'

#gem 'rails_12factor', group: :production

#ruby "2.1.0"